name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build JAR
        run: ./gradlew clean build shadowJar

      - name: Generate JavaDoc
        run: ./gradlew javadoc

      - name: Publish JavaDoc
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: build/docs/javadoc/

      - name: Publish JAR to GitHub Releases
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/libs/RunGame-1.0.0.jar
